spring.application.name=Unidades
# Puerto en el que corre este microservicio
server.port=8083

# Datos de conexión a MySQL de XAMPP
# Cambia 'nombre_de_tu_bd' por el nombre real de tu base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_bupa
spring.datasource.username=root
spring.datasource.password=

# Driver y Dialecto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Estrategia de creación de tablas (update para que no borre tus datos)
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola para ver qué está pasando
spring.jpa.show-sql=true

spring.flyway.enabled=false