spring.application.name=Inventario
spring.flyway.enabled=false

# Configuración para MySQL (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_bupa?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# Dialecto específico para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate creará las tablas en MySQL automáticamente según tus @Entity
spring.jpa.hibernate.ddl-auto=update

# Para ver las consultas SQL en la consola
spring.jpa.show-sql=true